### ISSUE TITLE
Switch to self_contained: false

### ISSUE THREAD

**Issue by awunderground** [UrbanInstitute/r-at-urban#23]
From [Bookdown](https://bookdown.org/yihui/rmarkdown/html-document.html#document-dependencies):

> One common reason to keep dependencies external is for serving R Markdown documents from a website (external dependencies can be cached separately by browsers, leading to faster page load times). In the case of serving multiple R Markdown documents you may also want to consolidate dependent library files (e.g. Bootstrap, and MathJax, etc.) into a single directory shared by multiple documents. You can use the lib_dir option to do this. For example:

```
---
title: "Habits"
output:
  html_document:
    self_contained: false
    lib_dir: libs
---
```
